"""add_llm_provider_configs_table

Revision ID: cb75d39778cb
Revises: 361e22d97199
Create Date: 2026-01-03 19:26:13.096152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb75d39778cb'
down_revision: Union[str, None] = '361e22d97199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.Enum('OPENAI', 'ANTHROPIC', 'GOOGLE', 'AZURE_OPENAI', 'OLLAMA', 'LLAMACPP', name='llmprovidertype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_provider_configs_id'), 'llm_provider_configs', ['id'], unique=False)
    op.create_index(op.f('ix_llm_provider_configs_provider_type'), 'llm_provider_configs', ['provider_type'], unique=False)
    op.create_index(op.f('ix_llm_provider_configs_user_id'), 'llm_provider_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_provider_configs_user_id'), table_name='llm_provider_configs')
    op.drop_index(op.f('ix_llm_provider_configs_provider_type'), table_name='llm_provider_configs')
    op.drop_index(op.f('ix_llm_provider_configs_id'), table_name='llm_provider_configs')
    op.drop_table('llm_provider_configs')
    # ### end Alembic commands ###
